# Generated by Django 5.1.7 on 2025-03-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('skills', models.CharField(max_length=1023)),
                ('link', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
