# Generated by Django 5.1.7 on 2025-03-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0003_remove_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.TextField(max_length=1023),
        ),
    ]
